Repository gin-gonic/gin, pull requests merged in 2018-09, with the labels that each got.

#1560 feat: replace debug log with fmt package.
  context_test.go
  debug.go
  debug_test.go
Labels: bug, enhancement

#1370 Don't log requests
  recovery.go
  recovery_test.go
Labels: bug, enhancement

#1570 Make logger use a yellow background and a darkgray text for legibility
  logger.go
  logger_test.go
Labels: enhancement

#1571 fix: fmt output log to os.Stderr
  debug.go
Labels: bug

#1574 chore: fix debug test error
  debug_test.go
Labels: bug
