Repository gin-gonic/gin, pull requests merged in 2018-06, with the labels that each got.

#1400 utils: use strings.Split instead of strings.IndexByte
  utils.go
Labels: enhancement

#1273 Add Pusher() function for support http2 server push
  README.md
  examples/http-pusher/assets/app.js
  examples/http-pusher/main.go
  examples/http-pusher/testdata/ca.pem
  examples/http-pusher/testdata/server.key
  examples/http-pusher/testdata/server.pem
  response_writer.go
  response_writer_1.7.go
  response_writer_1.8.go
Labels: feature

#1401 add grpc example
  Makefile
  coverage.sh
  examples/grpc/README.md
  examples/grpc/gin/main.go
  examples/grpc/grpc/server.go
  examples/grpc/pb/helloworld.pb.go
  examples/grpc/pb/helloworld.proto
Labels: document
