Repository gin-gonic/gin, pull requests merged in 2018-11, with the labels that each got.

#1619 Added some comments to avoid having golint warnings
  errors.go
  mode.go
Labels: document

#1617 Change HTML input tags to use HTML5 syntax.
  README.md
  examples/realtime-advanced/resources/room_login.templ.html
  examples/realtime-chat/template.go
Labels: document

#1618 Yaml binding
  README.md
  binding/binding.go
  binding/binding_body_test.go
  binding/binding_test.go
  binding/yaml.go
  context.go
  context_test.go
Labels: feature

#1609 feat(server): Implements RunFd method
  gin.go
  gin_integration_test.go
Labels: feature

#1259 Fix panic stack trace being printed during recovery of broken pipe (#1089)
  recovery.go
  recovery_test.go
Labels: bug, enhancement

#1650 Make sure the debug log contains line breaks
  debug.go
Labels: enhancement

#1640 recovery: fix issue about syscall import on google app engine
  recovery.go
  recovery_test.go
Labels: bug

#1612 support bind uri param
  README.md
  binding/binding.go
  binding/binding_test.go
  binding/form_mapping.go
  binding/uri.go
  context.go
  githubapi_test.go
  tree_test.go
Labels: feature

#1638 handle nil body for JSON binding
  binding/binding_test.go
  binding/json.go
Labels: bug

#1588 add chinese docs
  README_ZH.md
Labels: document

#1661 add picfit to gin user list
  README.md
Labels: document

#1659 update README_ZH.md
  README_ZH.md
Labels: document

#1663 Router: Route StaticFS() not found to Router's NoRoute()
  routergroup.go
  routes_test.go
Labels: enhancement
