Repository gin-gonic/gin, pull requests merged in 2018-05, with the labels that each got.

#1352 Fix typo in panic() message (extra single quote)
  tree.go
Labels: enhancement

#1341 Fix #216: Enable to call binding multiple times in some formats
  README.md
  binding/binding.go
  binding/binding_body_test.go
  binding/json.go
  binding/msgpack.go
  binding/protobuf.go
  binding/xml.go
  context.go
  context_test.go
Labels: feature

#1350 fix bug, return err when failed binding bool
  binding/binding_test.go
  binding/form_mapping.go
Labels: bug
