Repository gin-gonic/gin, pull requests merged in 2018-07, with the labels that each got.

#1418 chore: remove duplicate code
  gin.go
Labels: enhancement

#1421 update assert param(expect, actual) position
  errors_test.go
  response_writer_test.go
Labels: bug

#1358 add json ASCII string render
  README.md
  context.go
  context_test.go
  render/json.go
  render/render_test.go
Labels: feature

#1438 return json if jsonp has not callback
  context.go
  context_test.go
Labels: enhancement
