Repository gin-gonic/gin, pull requests merged in 2018-08, with the labels that each got.

#1383 Support map as query string or post form parameters
  README.md
  context.go
  context_test.go
Labels: feature

#1459 interface implement type check
  render/render.go
Labels: bug

#1473 improve utils code coverage
  utils_test.go
Labels: enhancement

#1474 improve render code coverage
  render/render_test.go
Labels: enhancement

#1481 add link for every referenced pull request
  CHANGELOG.md
Labels: document

#1490 Fix typo in readme
  README.md
Labels: document

#1491 chore: upgrade dependency library version
  vendor/vendor.json
Labels: enhancement

#1485 Add BindXML AND ShouldBindXML #1484
  README.md
  context.go
  context_test.go
Labels: feature

#1487 Set default time format in form binding
  binding/form_mapping.go
Labels: enhancement

#1492 Fix typo in README
  README.md
Labels: document

#1479 Add support for Protobuf format response and unit test
  README.md
  context.go
  context_test.go
  render/protobuf.go
  render/render.go
  render/render_test.go
Labels: feature

#1496 not use protobuf on context but use it on render
  context.go
  render/json.go
  render/protobuf.go
  render/render.go
  render/render_test.go
Labels: enhancement

#1498 render: update msgpack usage
  render/msgpack.go
Labels: enhancement

#1497 chore: add missing copyright and update if/else
  render/reader.go
  render/text.go
Labels: enhancement

#694 Add PureJSON renderer
  README.md
  context_17.go
  context_17_test.go
  context_test.go
  json/json.go
  render/json_17.go
  render/render_17_test.go
  render/render_test.go
Labels: feature, need-review

#1500 fix compile error for -tags=jsoniter
  json/jsoniter.go
Labels: bug

#1503 format readme code import
  README.md
Labels: document

#1509 Update README.md
  README.md
Labels: document

#1504 add internal package which includes json package
  binding/json.go
  errors.go
  errors_test.go
  internal/json/json.go
  internal/json/jsoniter.go
  render/json.go
  render/json_17.go
Labels: enhancement

#1505 docs: add fnproject to gin's user list
  README.md
Labels: document
