Repository gin-gonic/gin, pull requests merged in 2018-10, with the labels that each got.

#1565 removed use of sync.pool from HandleContext and added test coverage
  gin.go
  gin_integration_test.go
Labels: enhancement

#1592 fix(Makefile): golint to new URL
  Makefile
Labels: enhancement

#1593 refactor(Makefile): allow overriding default go program
  Makefile
  coverage.sh
Labels: enhancement

#1521 document: add docs dir and middleware document
  docs/how-to-build-an-effective-middleware.md
Labels: document

#1559 Fix LoadHTML* tests
  gin_integration_test.go
  gin_test.go
Labels: enhancement

#1599 Add example to set and get cookies
  README.md
Labels: document

#1601 docs: add photoprism to gin's user list
  README.md
Labels: document

#1600 Pass MaxMultipartMemory when FormFile is called
  context.go
  context_test.go
Labels: bug, enhancement
