Repository gin-gonic/gin, pull requests merged in 2019-03, with the labels that each got.

#1112 Support negotiation wildcards, fix #391
  context.go
  context_test.go
Labels: feature

#1260 Extend context.File to allow for the content-dispositon attachments via a new method context.Attachment
  context.go
  context_test.go
Labels: enhancement, feature

#1788 chore: add examples repo link to README
  README.md
  examples/README.md
Labels: document

#1790 Drone switch from gin to go-chi in 1.0 version.
  README.md
Labels: document

#1252 Added flag to context.Stream indicates if client disconnected in middle of stream
  context.go
Labels: enhancement

#1749 refactor(form_mapping.go): mapping ptr, struct and map
  README.md
  binding/binding_test.go
  binding/form_mapping.go
  binding/form_mapping_benchmark_test.go
Labels: enhancement, feature

#1794 add support time.Duration on mapping
  binding/binding_test.go
  binding/form_mapping.go
Labels: enhancement

#1791 chore: use internal/json
  binding/form_mapping.go
  internal/json/json.go
  internal/json/jsoniter.go
Labels: enhancement

#1779 make context.Keys available as LogFormatterParams
  logger.go
  logger_test.go
Labels: enhancement

#1805 fix #1804 which is caused by calling middleware twice.
  routergroup.go
  routes_test.go
Labels: bug

#1793 chore: update readme
  README.md
Labels: document

#1797 add support arrays on mapping
  binding/binding_test.go
  binding/form_mapping.go
Labels: enhancement

#1264 update for supporting file binding
  binding/binding.go
  binding/binding_test.go
  binding/form.go
  binding/form_mapping.go
Labels: feature

#1802 IsTerm flag should not be affected by DisableConsoleColor method.
  logger.go
  logger_test.go
Labels: enhancement

#1830 Truncate Latency precision in long running request
  logger.go
  logger_test.go
Labels: enhancement
