Repository gin-gonic/gin, pull requests merged in 2019-02, with the labels that each got.

#1530 Update: examples/graceful-shutdown/server.go
  README.md
  examples/graceful-shutdown/graceful-shutdown/server.go
Labels: document

#1724 Add a function to force color in console output
  README.md
  logger.go
  logger_test.go
Labels: enhancement

#1733 allow ignoring field on form mapping
  binding/binding_test.go
  binding/form_mapping.go
Labels: enhancement

#1752 Add response size to LogFormatterParams
  logger.go
Labels: enhancement

#1722 fix render writeHeaders method to make it the same as http.Header.Set
  render/reader.go
  render/render_test.go
Labels: enhancement

#1771 Change color methods in using defaultLogger function to public
  logger.go
  logger_test.go
Labels: enhancement

#1729 Add context.HandlerNames()
  context.go
  context_test.go
Labels: enhancement

#1020 Fix context.Copy() race condition
  context.go
  context_test.go
  githubapi_test.go
Labels: enhancement

#1238 add prefix from X-Forwarded-Prefix in redirectTrailingSlash
  gin.go
  routes_test.go
Labels: feature
