Repository gin-gonic/gin, pull requests merged in 2019-11, with the labels that each got.

#1943 fix ignore walking on form mapping (#1942)
  binding/form_mapping.go
  binding/form_mapping_test.go
Labels: bug

#2121 [FIX] allow empty headers on DataFromReader
  context_test.go
  render/reader.go
  render/reader_test.go
Labels: bug, enhancement

#2122 Changed wording for clarity in README.md
  README.md
Labels: document

#2149 upgrade go-validator to v10
  binding/default_validator.go
  binding/validate_test.go
  go.mod
  go.sum
Labels: enhancement

#2148 drop support govendor
  .travis.yml
  Makefile
  README.md
  vendor/vendor.json
Labels: enhancement

#1970 Refactor redirect request in gin.go
  binding/form.go
  gin.go
Labels: refactor

#2159 chore(performance): Improve performance for adding RemoveExtraSlash flag
  gin.go
  routes_test.go
Labels: break-backward, enhancement

#2155 use http method constant
  binding/binding.go
  gin.go
  gin_integration_test.go
  githubapi_test.go
  logger.go
  routergroup.go
  routergroup_test.go
  routes_test.go
Labels: enhancement

#2153 docs(benchmarks): for gin v1.5
  BENCHMARKS.md
Labels: document
