Repository gin-gonic/gin, pull requests merged in 2019-06, with the labels that each got.

#1920 feat: improve get post data.
  context.go
Labels: enhancement

#1923 use sse v0.1.0
  go.mod
  go.sum
  vendor/vendor.json
Labels: enhancement

#1922 use context instead of x/net/context
  context_test.go
  vendor/vendor.json
Labels: enhancement

#1931 Attempt to fix #1927
  context.go
Labels: bug

#1949 binding: add support of multipart multi files (#1878)
  README.md
  binding/form.go
  binding/multipart_form_mapping.go
  binding/multipart_form_mapping_test.go
Labels: enhancement

#1957 support bind http header param #1956
  README.md
  binding/binding.go
  binding/binding_test.go
  binding/header.go
  context.go
  context_test.go
Labels: feature

#1933 Drop Support for go1.8 and go1.9
  .travis.yml
  README.md
  debug.go
  debug_test.go
Labels: enhancement

#1919 Bugfix for the FullPath feature
  routes_test.go
  tree.go
Labels: bug

#1937 Add user case: brigade
  README.md
Labels: document

#1939 Gin1.5 bytes.Buffer to strings.Builder
  debug.go
  errors.go
Labels: enhancement
