Repository gin-gonic/gin, pull requests merged in 2019-09, with the labels that each got.

#2007 Fixed JSONP format (added semicolon)
  context_test.go
  render/json.go
  render/render_test.go
Labels: break-backward, bug

#1015 upgrade validator version to v9
  binding/binding_test.go
  binding/default_validator.go
  binding/validate_test.go
  go.mod
  go.sum
  vendor/vendor.json
Labels: break-backward, enhancement, need-review

#2011 Added specific installation instructions for Mac
  README.md
Labels: document

#2028 feat(binding): add DisallowUnknownFields() in gin.Context.BindJSON()
  binding/binding_test.go
  binding/json.go
  mode.go
  mode_test.go
Labels: feature

#2051 refactor(context.go): GetPostFormMap
  context.go
Labels: enhancement

#2052 Make countParams more readable
  tree.go
Labels: enhancement

#2067 Updated Readme.md for serving multiple services
  README.md
Labels: document

#2063 use url.URL.Query instead of parsing query
  context.go
Labels: refactor

#2071 add TestDisableBindValidation
  mode_test.go
Labels: enhancement

#2068 Updated Readme.md: file.Close() for template read
  README.md
Labels: document

#2023 support run HTTP server with specific net.Listener
  gin.go
  gin_integration_test.go
Labels: feature
