Repository gin-gonic/gin, pull requests merged in 2019-12, with the labels that each got.

#2163 tree: sync part httprouter codes and reduce if/else
  tree.go
Labels: enhancement

#2166 Fixed a bug in the calculation of the maximum number of parameters
  tree.go
  tree_test.go
Labels: bug

#2171 tree: sync httprouter update
  tree.go
Labels: enhancement

#2172 tree: sync httprouter update
  tree.go
Labels: enhancement

#2173 tree: sync httprouter update
  tree.go
Labels: enhancement

#2186 Fix "Custom Validators" example
  README.md
Labels: document

#2177 tree: remove one else statement
  tree.go
Labels: enhancement

#2188 Update to currently output
  README.md
Labels: document

#2189 upgrade go-validator to v10 for README
  README.md
Labels: document

#2190 Update validator to v10
  README.md
Labels: document

#2198 Remove broken link from README.
  README.md
Labels: document
