Repository gin-gonic/gin, pull requests merged in 2019-05, with the labels that each got.

#1817 Clean the Request Path early
  gin.go
  routes_test.go
Labels: enhancement

#1891 Use DefaultWriter and DefaultErrorWriter for debug messages
  debug.go
  debug_test.go
Labels: enhancement

#1886 add dev version
  README.md
  version.go
Labels: document

#1893 Now you can parse the inline lowercase start structure
  binding/binding_test.go
  binding/form_mapping.go
Labels: enhancement

#1909 Some code improvements
  binding/form_mapping.go
  context.go
  tree.go
Labels: enhancement

#1546 use encode replace json marshal increase json encoder speed
  context_test.go
  logger_test.go
  middleware_test.go
  render/json.go
  render/render_test.go
Labels: enhancement

#1826 Hold matched route full path in the Context
  README.md
  context.go
  gin.go
  routes_test.go
  tree.go
  tree_test.go
Labels: enhancement, need-review

#1841 Fix context.Params race condition on Copy()
  context.go
  context_test.go
Labels: bug

#1450 add context param query cache
  context.go
Labels: enhancement, need-review

#1918 chore: improve GetQueryMap performance.
  context.go
Labels: enhancement
