Repository gin-gonic/gin, pull requests merged in 2020-03, with the labels that each got.

#2112 FileFromFS
  README.md
  context.go
  context_test.go
Labels: feature

#2277 Add mitigation for log injection
  logger.go
  logger_test.go
Labels: enhancement

#2280 Unix Socket Handling
  gin.go
Labels: bug

#1391 Add mutex for protect Context.Keys map
  context.go
  gin.go
Labels: bug, enhancement

#2288 Improved the graceful shutdown and restart section and removed dead code
  README.md
Labels: document

#2294 Revert "fix accept incoming network connections"
  utils.go
Labels: bug

#2306 Add set samesite in cookie.
  context.go
  context_test.go
Labels: enhancement

#2305 fix missing initial sync.RWMutex
  context.go
  context_test.go
  go.sum
Labels: bug
