Repository gin-gonic/gin, pull requests merged in 2020-08, with the labels that each got.

#2448 Docs: Update README.md Custom Validator sample code
  README.md
Labels: document

#2450 binding: avoid 2038 problem on 32-bit architectures
  binding/form_mapping.go
Labels: enhancement

#2412 Prevent panic in Context.GetQuery() when there is no Request
  context.go
  context_test.go
Labels: bug
