Repository gin-gonic/gin, pull requests merged in 2020-05, with the labels that each got.

#2351 chore(performance): Change *sync.RWMutex to sync.RWMutex
  context.go
  gin.go
Labels: enhancement

#2354 chore: update the result of CR
  auth.go
  context.go
  gin.go
  mode.go
  path.go
  recovery.go
Labels: enhancement

#2356 chore: update some code style
  context.go
  gin.go
  githubapi_test.go
  internal/json/jsoniter.go
  routes_test.go
Labels: refactor

#2357 chore: update godoc address
  README.md
Labels: document

#2355 docs: update benchmark result v1.6.3
  BENCHMARKS.md
  README.md
Labels: document

#2358 Fix typo
  README.md
Labels: document

#2362 uncomment the code in README
  README.md
Labels: document

#2365 chore: improve render string performance
  render/text.go
Labels: enhancement

#2368 Sync route tree to httprouter latest code
  context.go
  gin.go
  tree.go
  tree_test.go
Labels: enhancement

#2366 fix(tree): reassign fullpath when register new node which the same current node
  routes_test.go
  tree.go
Labels: bug

#2375 chore: rename getQueryCache/getFormCache to initQueryCache/initFormCache
  context.go
  utils.go
Labels: refactor

#2378 chore(performance): improve countParams
  tree.go
Labels: enhancement

#2381 Broken link repo typo fix
  BENCHMARKS.md
Labels: document

#2387 Remove some functions that have the same effect as the bytes package
  tree.go
Labels: refactor

#2388 add miss copyright
  internal/bytesconv/bytesconv.go
  internal/bytesconv/bytesconv_test.go
Labels: document

#2391 remove a unused type SecureJSONPrefix
  render/json.go
Labels: enhancement

#2389 Add a redirect sample for POST method
  README.md
Labels: document

#2393 Rename some variables
  errors.go
  fs.go
  routergroup.go
Labels: refactor

#2395 DebugPrintRouteFunc() unit test
  debug_test.go
Labels: test
