Repository gin-gonic/gin, pull requests merged in 2020-01, with the labels that each got.

#2202 Fix spelling
  CHANGELOG.md
  context.go
Labels: document

#2179 Reuse bytes when cleaning the URL paths
  path.go
  path_test.go
Labels: enhancement

#2196 Update docs on Context.Done(), Context.Deadline() and Context.Err()
  context.go
Labels: document

#2212 path: sync code with httprouter
  path.go
Labels: enhancement

#2206 Use zero-copy approach to convert types between string and byte slice
  auth.go
  binding/form_mapping.go
  gin.go
  internal/bytesconv/bytesconv.go
  internal/bytesconv/bytesconv_test.go
  render/json.go
Labels: enhancement

#1615 Added support for SameSite cookie flag
  context.go
  context_test.go
Labels: break-backward, enhancement

#2215 chore: upgrade go-isatty and json-iterator/go
  go.mod
  go.sum
Labels: enhancement

#2217 Renew README to fit the modification of SetCookie method
  README.md
Labels: document

#2223 docs(path): improve comments
  path.go
  tree.go
Labels: document

#2222 tree: remove duplicate assignment
  tree.go
Labels: enhancement
