Repository gin-gonic/gin, pull requests merged in 2020-02, with the labels that each got.

#2220 add yaml negotitation
  context.go
  context_test.go
Labels: feature

#2229 tree: range over nodes values
  tree.go
Labels: enhancement

#2240 docs(badge): add todo badge
  README.md
Labels: document

#2228 Use json marshall in context json to fix breaking new line issue. Fixes #2209
  context_test.go
  logger_test.go
  middleware_test.go
  render/json.go
  render/render_test.go
Labels: bug
