Repository gin-gonic/gin, pull requests merged in 2020-10, with the labels that each got.

#2500 use IndexByte replace Split to improve performance
  utils.go
  utils_test.go
Labels: enhancement

#2528 fix: print headers without Authorization header on broken pipe
  recovery.go
Labels: enhancement

#2519 Add some missing dots on README
  README.md
Labels: document

#2508 reduce allocs and improve the render `WriteString`
  render/text.go
Labels: enhancement

#2526 implement ".Unwrap() error" on Error type (#2525)
  errors.go
  errors_1.13_test.go
Labels: feature

#2536 upgrade go-validator to v10.4.1
  go.mod
  go.sum
Labels: enhancement

#2540 ci: romove go1.11 for gin1.7
  .travis.yml
  README.md
Labels: enhancement

#2484 Allow bind with a map[string]string
  binding/binding_test.go
  binding/form_mapping.go
  binding/json_test.go
Labels: feature
