Repository gin-gonic/gin, pull requests merged in 2021-07, with the labels that each got.

#2772 Fix typo
  context.go
Labels: document

#2774 byte alignment
  gin.go
Labels: refactor

#2780 update the version of validator in the comment
  binding/binding.go
  binding/binding_nomsgpack.go
Labels: document

#2776 Use bit shift operation instead of division
  context.go
Labels: document, refactor

#2782 Use std http method constant instead of raw string
  gin.go
Labels: enhancement

#2783 use assert1 func
  routergroup.go
Labels: test

#2787 Improve router group tests
  routergroup_test.go
Labels: test

#2767 fix #2762
  gin_integration_test.go
  tree.go
  tree_test.go
Labels: bug

#2796 fix #2786
  gin_integration_test.go
  tree.go
  tree_test.go
Labels: bug

#2797 fix readability in recovery test
  recovery_test.go
Labels: test

#2769 fallback Context.Deadline() Context.Done() Context.Err() to Context.Request.Context()
  context.go
  context_test.go
Labels: enhancement
