Repository gin-gonic/gin, pull requests merged in 2021-01, with the labels that each got.

#2600 fix compile error from #2572
  internal/bytesconv/bytesconv.go
Labels: enhancement

#2371 chore: update tree
  tree.go
Labels: refactor

#2302 Support binding for slice/array obj [Rewrite]
  binding/binding.go
  binding/binding_test.go
  binding/default_validator.go
  binding/default_validator_test.go
Labels: feature

#2538 Adding ppc64le architecture support on travis-ci
  .travis.yml
Labels: enhancement

#2595 test: fixed the TestUnixSocket test on windows
  gin_integration_test.go
Labels: test

#2567 "gin mode unknown" error: show available mode
  mode.go
Labels: document

#2584 fix error gin support min Go version
  debug.go
  debug_test.go
Labels: document

#2552 Fixes to the graceful shutdown example
  README.md
Labels: enhancement

#2609 basic auth: fix timing oracle
  auth.go
Labels: enhancement

#2622 chore: Deleted spaces
  .travis.yml
  AUTHORS.md
  BENCHMARKS.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: document
