Repository gin-gonic/gin, pull requests merged in 2021-09, with the labels that each got.

#2856 Fix go1.17 test error
  context_1.16_test.go
  context_1.17_test.go
  context_test.go
Labels: test

#2828 chore: Add go1.17 for testing
  .github/workflows/gin.yml
Labels: enhancement

#2858 bump golangci-lint version
  .github/workflows/gin.yml
Labels: continuous-integration

#2848 gin.Context.SetParam shortcut for e2e tests
  context.go
  context_test.go
Labels: enhancement

#2851 fix: check obj type in protobufBinding
  binding/binding_test.go
  binding/protobuf.go
Labels: enhancement

#2861 fixed SetOutput() panics on go 1.17
  go.mod
  go.sum
Labels: bug, dependencies

#2870 golangci(lint) : more linters
  .github/workflows/gin.yml
  .golangci.yml
  binding/form.go
  context.go
  context_test.go
  recovery.go
  render/render_test.go
Labels: refactor, continuous-integration

#2880 Correcting grammatical errors in README file
  README.md
Labels: document

#2882 Add gosec
  .golangci.yml
Labels: continuous-integration

#2883 Fix grammatical and spelling errors in context.go
  context.go
Labels: document

#2832 Quick Fix c.ClientIP() mistakely parsing to 127.0.0.1 for who not using r.Run() to run http server
  gin.go
  middleware_test.go
Labels: enhancement
