Repository gin-gonic/gin, pull requests merged in 2021-04, with the labels that each got.

#2663 Add mixed param and non-param paths (port of httprouter#329)
  AUTHORS.md
  CHANGELOG.md
  README.md
  tree.go
  tree_test.go
Labels: enhancement, feature

#2632 feat(engine): add trustedproxies and remoteIP
  README.md
  context.go
  context_test.go
  gin.go
  gin_integration_test.go
  gin_test.go
Labels: bug

#2672 bump to v1.7.0 version
  CHANGELOG.md
  version.go
Labels: document

#2675 fix: data race with trustedCIDRs (#2674)
  context.go
  context_test.go
  logger_test.go
Labels: bug

#2679 Remove go1.12 support
  .travis.yml
  README.md
  debug.go
  debug_test.go
  errors_1.13_test.go
  errors_test.go
Labels: enhancement

#2638 support Go v1.16 version
  .travis.yml
  context_test.go
  routes_test.go
Labels: break-backward

#2694 Use `Header()` instead of deprecated `HeaderMap`
  context_test.go
Labels: enhancement

#2707 use errors.New to replace fmt.Errorf will much better
  binding/json.go
Labels: enhancement
