Repository gin-gonic/gin, pull requests merged in 2021-11, with the labels that each got.

#2924 fix tsr with mixed static and wildcard paths
  tree.go
  tree_test.go
Labels: bug

#2923 Update version.go
  version.go
Labels: enhancement

#2929 Bump golangci-lint version
  .github/workflows/gin.yml
Labels: test

#2933 Fix grammar
  context.go
Labels: document

#2777 Export struct sliceValidateError to allow error casting
  binding/default_validator.go
  binding/default_validator_benchmark_test.go
  binding/default_validator_test.go
Labels: enhancement

#2958 fix: typo
  gin.go
Labels: document

#2961 fix: description error
  context.go
Labels: document

#2954 FIX hash link typo at README.md
  README.md
Labels: document

#2934 prettify error message for catch-all conflict with existing path segment
  tree.go
Labels: enhancement, document

#2968 fix: description error
  context.go
  gin.go
Labels: document
