Repository gin-gonic/gin, pull requests merged in 2021-08, with the labels that each got.

#2802 docs: release v1.7.3
  CHANGELOG.md
  version.go
Labels: document

#2804 catch error from examples
  README.md
Labels: document

#2827 chore(ci): update dependencies
  .github/dependabot.yml
  .github/workflows/gin.yml
  .golangci.yml
  binding/binding_test.go
  binding/form_mapping.go
  binding/form_mapping_test.go
  binding/protobuf.go
  binding/uri.go
  context_test.go
  go.mod
  go.sum
  mode.go
  render/json.go
  render/protobuf.go
  render/render_test.go
  response_writer_test.go
  testdata/protoexample/test.pb.go
  tree_test.go
Labels: enhancement

#2829 chore(ci): golangci timeout
  .golangci.yml
Labels: enhancement

#2830 Delete unused static const
  tree.go
Labels: refactor

#2834 Delete unused arg
  binding/form_mapping.go
Labels: enhancement

#2839 bump golangci-lint
  .github/workflows/gin.yml
Labels: continuous-integration

#2838 Delete deadcode exclude rules
  .golangci.yml
Labels: continuous-integration

#2837 Add short func with named return
  context.go
Labels: refactor

#2788 minor tweaks,optimize code
  render/json.go
Labels: enhancement
