Repository gin-gonic/gin, pull requests merged in 2021-06, with the labels that each got.

#2700 Optimize code adjust
  binding/form_mapping.go
  binding/header.go
  binding/multipart_form_mapping.go
  render/json.go
Labels: enhancement

#2756 updated comments for Get function for params
  tree.go
Labels: document

#2596 ci: add github action workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gin.yml
  .travis.yml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: test

#2739 Setting trusted platform using an enum-like
  context.go
  context_appengine.go
  context_test.go
  gin.go
Labels: enhancement

#2760 fix typo and add comments
  recovery.go
Labels: document

#2761 Skip unnecessary variable assignment in timeFormat
  recovery.go
Labels: refactor

#2764 Use buf.String() instead of string(buf.Bytes())
  render/msgpack.go
  render/render_msgpack_test.go
Labels: document, test

#2755 Fix insufficient slice check
  tree.go
  tree_test.go
Labels: bug

#2765 Improve `sliceValidateError.Error` performance
  binding/default_validator.go
  binding/default_validator_benchmark_test.go
  binding/default_validator_test.go
Labels: enhancement, refactor

#2720 feat(binding): support custom struct tag
  README.md
  binding/form_mapping.go
  binding/form_mapping_test.go
Labels: enhancement
