Repository gin-gonic/gin, pull requests merged in 2021-05, with the labels that each got.

#2710 Fix example code of `Bind Uri`
  README.md
Labels: document

#2703 Add note about `nomsgpack` tag to the readme
  README.md
Labels: document

#2711 Use `Duration.Truncate` for truncating precision
  logger.go
Labels: enhancement

#2706 Fix conflict between param and exact path
  tree.go
  tree_test.go
Labels: bug

#2715 README.md update
  README.md
Labels: document

#2724 chore(docs): bump to v1.7.2
  CHANGELOG.md
  version.go
Labels: document

#2722 optimize code
  context.go
Labels: refactor

#2729 upgrade validator to v10.6.1
  go.mod
  go.sum
Labels: enhancement

#2716 Check multipart file header size on test
  binding/multipart_form_mapping_test.go
Labels: enhancement

#2732 Upgrade github.com/ugorji/go/codec
  go.mod
  go.sum
Labels: enhancement

#2692 set engine.TrustedProxies For items that don't use gin.RUN
  context_test.go
  gin.go
  gin_integration_test.go
Labels: enhancement

#2738 Update default validator's docs link
  binding/default_validator.go
Labels: document

#2723 Get client IP when using Cloudflare
  context.go
  context_test.go
  gin.go
Labels: enhancement
