Repository gin-gonic/gin, pull requests merged in 2022-12, with the labels that each got.

#3414 docs(context): #3369 modify the annotation about Context.Param()
  context.go
Labels: document

#3432 Fix the GO-2022-1144 vulnerability
  go.mod
  go.sum
Labels: security

#3420 docs(readme): release v1.8.2 version
  CHANGELOG.md
  version.go
Labels: document

#3433 refactor: avoid calling strings.ToLower twice
  recovery.go
Labels: refactor

#3401 test(TOML): Add some tests for the TOML render
  render/render_test.go
Labels: test
