Repository gin-gonic/gin, pull requests merged in 2022-10, with the labels that each got.

#3333 Fix the GO-2022-0969 and GO-2022-0288 vulnerabilities
  .github/workflows/gin.yml
  go.mod
  go.sum
Labels: security

#3361 chore(dep): Changes minimum support go version to go1.16
  README.md
  debug.go
  debug_test.go
Labels: document, continuous-integration

#3272 chore(go): Add support go 1.19
  .github/workflows/gin.yml
  context_1.17_test.go
  context_1.19_test.go
Labels: enhancement, continuous-integration

#3325 fix(typo): spelling `covert` -> `convert`
  binding/form_mapping.go
Labels: document

#3345 refactor(struct): Remove redundant type conversions
  binding/binding_test.go
  binding/form_mapping_test.go
  render/render_test.go
Labels: refactor, test

#3327 fix: modify interface check way
  binding/default_validator.go
  context_test.go
  errors.go
  gin.go
  response_writer.go
  routergroup.go
Labels: refactor
