Repository gin-gonic/gin, pull requests merged in 2022-08, with the labels that each got.

#3260 docs: update markdown format
  README.md
Labels: document

#3278 chore: upgrade golangci-lint and fix golangci-lint error
  .github/workflows/gin.yml
  context.go
  context_test.go
  errors.go
  errors_test.go
  ginS/gins.go
  logger_test.go
  middleware_test.go
  mode.go
  path.go
  recovery.go
  routergroup.go
Labels: document, continuous-integration

#3277 Format with Go 1.19 formatter
  .github/workflows/gin.yml
Labels: continuous-integration

#3304 GitHub Workflows security hardening
  .github/workflows/gin.yml
Labels: continuous-integration

#3302 Fix typos in RouterGroup method docs
  routergroup.go
Labels: document
