Repository gin-gonic/gin, pull requests merged in 2022-11, with the labels that each got.

#2803 fix(engine): missing route params for CreateTestContext (#2778)
  context_test.go
  gin.go
  test_helpers.go
Labels: bug

#3376 docs(readme): Update some go website links
  README.md
Labels: document

#3328 fix: test fmt.Println replace t.Error
  gin_test.go
Labels: refactor, test

#3379 docs(readme): Using the embed package as a recommended example that build a single binary with templates
  README.md
Labels: document

#3394 docs(readme): Modify sample code bugs
  README.md
Labels: document

#3395 remove deprecated of package io/ioutil
  binding/binding_test.go
  binding/multipart_form_mapping_test.go
  binding/protobuf.go
  context.go
  gin_integration_test.go
  gin_test.go
  recovery.go
  routes_test.go
Labels: refactor

#3400 docs(readme): Add the TOML rendering example
  README.md
Labels: document
