Repository gin-gonic/gin, pull requests merged in 2022-05, with the labels that each got.

#3139 feat: automatically SetMode to TestMode when run go test.
  mode.go
  mode_test.go
Labels: enhancement

#3033 fix: default trusted proxies should add ipv6
  gin.go
Labels: enhancement

#3081 [GIN-001] - Add TOML bining for gin
  README.md
  binding/binding.go
  binding/binding_nomsgpack.go
  binding/binding_test.go
  binding/toml.go
  binding/toml_test.go
  context.go
  context_test.go
  go.mod
  go.sum
  render/render.go
  render/toml.go
Labels: feature

#3159 chore(CI/CD): add go version release flow
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
  version.go
Labels: continuous-integration

#3160 add v1.8.0 changelog
  AUTHORS.md
  CHANGELOG.md
  binding/toml.go
  binding/uri.go
  render/render_msgpack_test.go
Labels: document
