Repository gin-gonic/gin, pull requests merged in 2022-02, with the labels that each got.

#3044 fix typo
  tree.go
Labels: document

#3037 ci: bump golangci-lint version
  .github/workflows/gin.yml
Labels: test

#3049 feat(CodeQL): Discover vulnerabilities across a codebase with CodeQL
  .github/workflows/codeql.yml
  go.mod
Labels: enhancement

#1398 support h2c with prior knowledge
  gin.go
  gin_test.go
  go.mod
  go.sum
Labels: feature

#3050 feat: fix lint error
  gin_test.go
Labels: enhancement

#3056 Update routergroup.go
  routergroup.go
Labels: document
