Repository gin-gonic/gin, pull requests merged in 2022-03, with the labels that each got.

#3076 doc: change the form name of upload example code
  README.md
Labels: document

#3083 Distinguish between group and nested group
  README.md
Labels: document

#3071 feat attachment filename support utf8
  context.go
  context_test.go
  utils.go
  utils_test.go
Labels: enhancement

#2749 feat: add StaticFileFS
  README.md
  routergroup.go
  routergroup_test.go
  routes_test.go
Labels: enhancement

#3087 fix: test error
  routes_test.go
Labels: bug, test

#3088 Annotation fix
  tree.go
Labels: document

#2990 test support go1.18
  any.go
  binding/any.go
  binding/binding.go
  binding/binding_nomsgpack.go
  binding/binding_test.go
  binding/default_validator.go
  binding/default_validator_test.go
  binding/form.go
  binding/form_mapping.go
  binding/form_mapping_test.go
  binding/header.go
  binding/json.go
  binding/msgpack.go
  binding/msgpack_test.go
  binding/multipart_form_mapping_test.go
  binding/protobuf.go
  binding/query.go
  binding/uri.go
  binding/validate_test.go
  binding/xml.go
  binding/yaml.go
  context.go
  context_test.go
  debug.go
  deprecated.go
  errors.go
  errors_test.go
  gin.go
  gin_test.go
  logger.go
  logger_test.go
  recovery.go
  recovery_test.go
  render/any.go
  render/html.go
  render/json.go
  render/msgpack.go
  render/protobuf.go
  render/render_msgpack_test.go
  render/render_test.go
  render/text.go
  render/xml.go
  render/yaml.go
  testdata/protoexample/any.go
  testdata/protoexample/test.pb.go
  tree_test.go
  utils.go
Labels: enhancement

#2964 chore: support min version of go: 1.14
  .github/workflows/gin.yml
  README.md
  debug.go
  debug_test.go
Labels: continuous-integration

#3092 chore(CI/CD): add go1.18 version
  .github/workflows/gin.yml
  go.mod
  go.sum
Labels: continuous-integration

#3090 Update some comments, add function name prefix to comment
  gin.go
  logger.go
  response_writer.go
Labels: document
