Repository gin-gonic/gin, pull requests merged in 2022-04, with the labels that each got.

#3108 docs: Update README.md
  README.md
Labels: document

#3123 Fix: missing `sameSite` when do context.reset()
  context.go
Labels: bug

#3100 Fix some tests
  gin_integration_test.go
  gin_test.go
  logger_test.go
  testdata/template/raw.tmpl
Labels: test

#3129 fix: removed YODA conditions, removed blank identifier from `invalid_obj`
  binding/binding_test.go
  githubapi_test.go
Labels: break-backward, refactor

#2798 use StringToBytes func
  auth.go
Labels: enhancement

#2825 feat(context): return GIN Context from Value method
  context.go
  context_test.go
Labels: feature
