Repository gin-gonic/gin, pull requests merged in 2023-01, with the labels that each got.

#3449 docs(readme): move more example to docs/doc.md
  README.md
  docs/doc.md
Labels: document

#3453 console logger HTTP status code bug fixed
  response_writer.go
  response_writer_test.go
Labels: enhancement

#3429 update context.go Get/Set method use defer
  context.go
Labels: refactor

#3456 chore(yaml): upgrade dependency to v3 version
  binding/yaml.go
  go.mod
  go.sum
  render/render_test.go
  render/yaml.go
Labels: enhancement, dependencies

#3446 docs: update markdown format
  docs/doc.md
Labels: document

#3460 fix(router): tree bug where loop index is not decremented.
  routes_test.go
  tree.go
Labels: bug, enhancement

#3397 fix(context): panic on NegotiateFormat - index out of range
  context.go
  context_test.go
Labels: bug

#3347 Replace bytes.Buffer with strings.Builder where appropriate
  debug_test.go
  githubapi_test.go
  logger_test.go
  recovery_test.go
Labels: refactor, test
