Repository gin-gonic/gin, pull requests merged in 2023-04, with the labels that each got.

#3575 docs: changed documentation link for trusted proxies
  gin.go
Labels: document

#3583 chore: improve linting, testing, and GitHub Actions setup
  .github/workflows/gin.yml
  .golangci.yml
  README.md
  codecov.yml
  fs.go
  recovery.go
Labels: enhancement, continuous-integration

#3585 chore: update dependencies for various packages and libraries
  go.mod
  go.sum
Labels: dependencies
