Repository gin-gonic/gin, pull requests merged in 2023-02, with the labels that each got.

#3464 chore(router): match method added to routergroup for multiple HTTP methods supporting
  routergroup.go
  routergroup_test.go
Labels: enhancement

#2150 Stop useless panicking in context and render
  context.go
  context_test.go
  render/json.go
  render/render_test.go
Labels: enhancement, break-backward

#3484 chore(go): Add support go 1.20
  .github/workflows/gin.yml
  go.mod
  go.sum
Labels: enhancement, dependencies

#3489 chore(http): add support for go1.20 http.rwUnwrapper to gin.responseWriter
  response_writer.go
  response_writer_test.go
Labels: enhancement

#3500 Add escape logic for header
  gin.go
  routes_test.go
Labels: bug

#3474 docs(readme): release v1.9.0 version
  CHANGELOG.md
  go.mod
  go.sum
  version.go
Labels: document
