Repository gin-gonic/gin, pull requests merged in 2024-10, with the labels that each got.

#4079 docs(context): fix some function names in comment
  context_test.go
Labels: document

#4078 docs(readme): add Portuguese documentation.
  README.md
Labels: document

#4070 docs: trimmed some white spaces
  docs/doc.md
Labels: document

#4066 fix: fix typo for c.ShouldBindBodyWithPlain comment
  context.go
  context_test.go
Labels: enhancement, continuous-integration

#4064 docs(gin): Replace broken link to documentation with valid
  gin.go
Labels: document

#4077 fix(tree): Keep panic infos consistent when wildcard type build faild
  .github/workflows/gin.yml
  tree.go
  tree_test.go
Labels: bug, enhancement

#4080 refactor(context): simplify "GetType()" functions
  context.go
Labels: refactor
