Repository gin-gonic/gin, pull requests merged in 2024-03, with the labels that each got.

#3859 chore(perf): Optimize the Copy method of the Context struct
  context.go
Labels: enhancement

#3863 test(http): use constant instead of numeric literal
  routes_test.go
Labels: test

#3851 chore(header): Add support for RFC 9512: application/yaml
  binding/binding.go
  binding/binding_nomsgpack.go
  binding/binding_test.go
  context_test.go
  render/render_test.go
  render/yaml.go
Labels: enhancement

#3868 docs: fix typo in comment
  routes_test.go
Labels: document

#3784 fix(route): Add fullPath in context copy
  context.go
  context_test.go
Labels: enhancement

#3855 chore(refactor): modify interface check way
  render/render.go
Labels: enhancement, refactor

#3370 test(git): gitignore add develop tools
  .gitignore
Labels: test

#3877 feat(auth): add proxy-server authentication
  auth.go
  auth_test.go
Labels: feature

#3873 fix: protect Context.Keys map when call Copy method
  context.go
Labels: bug

#3872 docs: fix typo in function documentation
  context.go
Labels: document

#3572 feat(engine): Added `OptionFunc` and `With`
  context_test.go
  gin.go
  gin_test.go
Labels: feature

#3419 chore(request): check reader if it's nil before reading
  context.go
Labels: enhancement

#3878 fix(engine): fix unit test
  context_test.go
Labels: test

#3881 Add document comments to function `BasicAuthForProxy`
  auth.go
Labels: document

#3880 docs(context): Added deprecation comments to BindWith
  deprecated.go
Labels: document

#3887 docs: Add document to constant `AuthProxyUserKey` and `BasicAuthForProxy`.
  auth.go
Labels: document

#3883 test(path): Optimize unit test execution results
  path_test.go
Labels: test

#3893 chore(security): upgrade Protobuf for CVE-2024-24786
  go.mod
  go.sum
Labels: security

#3891 build(codecov): Added a codecov configuration
  codecov.yml
Labels: test

#3236 fix(uri): query binding bug
  binding/query.go
  binding/query_test.go
Labels: bug

#3899 Revert "fix(uri): query binding bug"
  binding/query.go
  binding/query_test.go
Labels: need-review, test

#3514 feat(binding): support override default binding implement
  binding/binding.go
Labels: feature

#3871 feat: ShouldBindBodyWith shortcut and change doc
  context.go
  context_test.go
  docs/doc.md
Labels: enhancement
