Repository gin-gonic/gin, pull requests merged in 2024-02, with the labels that each got.

#3834 ci(lint): update tooling and workflows for consistency
  .github/workflows/gin.yml
  .golangci.yml
  go.sum
  tree.go
Labels: continuous-integration

#3835 chore(deps): update dependencies to latest versions
  .github/workflows/gin.yml
  go.mod
  go.sum
Labels: dependencies

#3593 feat(logger): ability to skip logs based on user-defined logic
  docs/doc.md
  logger.go
  logger_test.go
Labels: feature

#3820 fix(binding): binding error while not upload file (#3819)
  binding/form_mapping.go
  binding/form_mapping_test.go
Labels: bug

#3759 fix(header): Allow header according to RFC 7231 (HTTP 405)
  gin.go
  routes_test.go
Labels: bug

#3199 fix(binding): dereference pointer to struct when validating structs
  binding/default_validator.go
  binding/validate_test.go
Labels: bug

#3839 chore(IP): add TrustedPlatform constant for Fly.io.
  context_test.go
  docs/doc.md
  gin.go
Labels: enhancement

#3842 ci(testing): add go1.22 version
  .github/workflows/gin.yml
  .github/workflows/goreleaser.yml
Labels: continuous-integration

#3848 chore(deps): refactor CI and update dependencies
  .github/workflows/gin.yml
  go.mod
  go.sum
Labels: continuous-integration, dependencies
