Repository gin-gonic/gin, pull requests merged in 2024-06, with the labels that each got.

#2857 feat(router): add literal colon support (#1432)
  gin.go
  gin_integration_test.go
  tree.go
  tree_test.go
Labels: enhancement

#3985 docs(readme): replace godoc with pkg
  README.md
Labels: document

#3997 docs: fix typo in Gin Quick Start
  docs/doc.md
Labels: document

#4003 fix(gin): Do not panic when handling method not allowed on empty tree
  gin.go
  gin_test.go
Labels: bug
