Repository gin-gonic/gin, pull requests merged in 2024-04, with the labels that each got.

#3911 chore(optimize): the ShouldBindUri method of the Context struct
  context.go
Labels: enhancement

#3915 ci(Makefile): vet command add .PHONY
  Makefile
Labels: continuous-integration

#3914 ci(release): refactor changelog regex patterns and exclusions
  .goreleaser.yaml
Labels: continuous-integration

#3901 chore: update various Go dependencies to latest versions
  go.mod
  go.sum
Labels: continuous-integration, dependencies
