Repository gin-gonic/gin, pull requests merged in 2024-05, with the labels that each got.

#3933 feat(binding): Support custom BindUnmarshaler for binding.
  binding/form_mapping.go
  binding/form_mapping_test.go
  docs/doc.md
  gin_test.go
Labels: feature

#3950 chore: update external dependencies to latest versions
  go.mod
  go.sum
Labels: security

#3951 ci: refactor configuration files for better readability
  .goreleaser.yaml
Labels: continuous-integration

#3952 docs: update version constant to v1.10.0
  version.go
Labels: document

#3953 docs: update documentation and release notes for Gin v1.10.0
  CHANGELOG.md
Labels: document

#3955 docs(engine): fix comments for the `With`
  gin.go
Labels: document

#3522 refactor(binding): use strings.Cut to replace strings.Index
  binding/form_mapping.go
Labels: refactor

#3945 docs(gin): update link to dont-trust-all-proxies section (#3938)
  gin.go
Labels: document

#3957 chore: support go 1.20 and set min version to go1.20
  .github/workflows/gin.yml
  context_1.18_test.go
  context_1.19_test.go
  context_test.go
  debug.go
  debug_test.go
  internal/bytesconv/bytesconv.go
  internal/bytesconv/bytesconv_1.19.go
Labels: enhancement, continuous-integration

#3939 feat(fs): Export, test and document OnlyFilesFS
  fs.go
  fs_test.go
  routergroup.go
Labels: document, test

#3210 feat(gin): support http3 using quic-go/quic-go
  .github/workflows/gin.yml
  .golangci.yml
  gin.go
  gin_integration_test.go
  go.mod
  go.sum
Labels: feature

#3960 build: update Gin minimum Go version to 1.21
  .github/workflows/gin.yml
  README.md
  debug.go
  debug_test.go
Labels: enhancement

#3961 fix(go): invalid Go toolchain version
  go.mod
Labels: continuous-integration, github_actions

#3964 ci(Makefile): added help and descriptions to targets
  Makefile
Labels: continuous-integration

#3904 feat(binding): add BindPlain
  binding/binding.go
  binding/binding_nomsgpack.go
  binding/binding_test.go
  binding/plain.go
  context.go
  context_test.go
Labels: feature

#3962 docs(readme): fix language and moved link
  README.md
Labels: document

#3910 refactor(slice): simplify SliceValidationError Error method
  binding/default_validator.go
  binding/default_validator_benchmark_test.go
Labels: enhancement, refactor

#3413 fix(context): check handler is nil
  context.go
  context_test.go
Labels: bug

#3966 fix(context): YAML judgment logic in Negotiate
  context.go
  context_test.go
Labels: enhancement

#3969 fix(context): verify URL is Non-nil in initQueryCache()
  context.go
  context_test.go
Labels: enhancement

#3971 feat(form): add custom string slice for form tag unmarshal (#3970)
  binding/form_mapping.go
  binding/form_mapping_test.go
Labels: enhancement

#3975 chore(tree): replace the self-defined 'min' to official one
  tree.go
Labels: enhancement, refactor
