Repository gin-gonic/gin, pull requests merged in 2024-11, with the labels that each got.

#4087 chore(context): test context initialization and handler logic
  context.go
  context_test.go
Labels: bug, enhancement

#4090 ci(lint): enable perfsprint linter
  .golangci.yml
  binding/form_mapping_test.go
  context_test.go
  gin_test.go
  githubapi_test.go
  recovery_test.go
  routes_test.go
Labels: enhancement, continuous-integration

#4091 ci(lint): enable usestdlibvars linter
  .golangci.yml
  auth_test.go
  benchmarks_test.go
  binding/binding_msgpack_test.go
  binding/binding_test.go
  binding/multipart_form_mapping_test.go
  context_test.go
  debug_test.go
  deprecated_test.go
  gin_test.go
  logger_test.go
  middleware_test.go
  recovery_test.go
  render/render_test.go
  routes_test.go
  utils_test.go
Labels: refactor

#4088 refactor(context): (reupload) Added an optional permission parameter to the SaveUploadedFile method (#4068)
  context.go
  context_test.go
Labels: enhancement, feature
