Repository gin-gonic/gin, pull requests merged in 2025-03, with the labels that each got.

#4185 docs: fix case error of X-Real-IP
  CHANGELOG.md
  context.go
Labels: document

#4167 fix: move fiximports to goimports section in golangci.yml
  .golangci.yml
Labels: continuous-integration, github_actions

#4190 feat(binding): add support for unixMilli and unixMicro (see #2634)
  binding/binding_test.go
  binding/form_mapping.go
  docs/doc.md
Labels: feature

#4193 fix(binding): prevent duplicate decoding and add validation in decodeToml
  binding/toml.go
Labels: bug
