Repository gin-gonic/gin, pull requests merged in 2025-09, with the labels that each got.

#4339 perf(context): optimize getMapFromFormData performance
  context.go
  context_test.go
Labels: performance

#4353 refactor(render): remove headers parameter from writeHeader
  render/reader.go
Labels: refactor

#4342 build(deps): upgrade github.com/bytedance/sonic from v1.13.2 to v1.14.0
  context_test.go
  go.mod
  go.sum
Labels: enhancement

#4341 ci: support Go 1.25
  .github/workflows/gin.yml
Labels: continuous-integration

#4359 ci: integrate Trivy vulnerability scanning into CI workflow
  .github/workflows/gin.yml
Labels: continuous-integration

#4363 docs: announce Gin 1.11.0 release with blog link
  README.md
Labels: document

#4364 docs: revamp GitHub contribution and support templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: continuous-integration

#4314 refactor(ginS): use sync.OnceValue to simplify engine function
  ginS/gins.go
Labels: refactor

#4373 fix(response): refine hijack behavior for response lifecycle
  response_writer.go
  response_writer_test.go
Labels: type/bug, enhancement

#4375 test(benchmarks): fix the incorrect function name
  benchmarks_test.go
Labels: test
