Repository gin-gonic/gin, pull requests merged in 2025-05, with the labels that each got.

#4234 fix: sonic on arm64
  .github/workflows/gin.yml
  docs/doc.md
  go.mod
  go.sum
  internal/json/json.go
  internal/json/sonic.go
Labels: enhancement

#4232 fix(errors): change Unwrap method receiver to value type
  errors.go
  errors_test.go
Labels: enhancement

#4244 test(lint): fix lint failures
  gin_test.go
Labels: continuous-integration

#4235 test(internal/fs): fix test function name
  internal/fs/fs_test.go
Labels: test

#4239 perf(all): use strings.Cut to replace strings.SplitN
  recovery.go
  tree.go
Labels: performance

#4240 feat(context): add SetCookieData
  context.go
  context_test.go
  docs/doc.md
Labels: feature

#4134 docs(readme): add gin-gonic/contrib
  README.md
Labels: document

#4115 fix(context): useless asserts
  context_test.go
Labels: enhancement

#4247 ci(golangci-lint): update configuration and fix lint issues
  .github/workflows/gin.yml
  .golangci.yml
  binding/binding_test.go
  binding/default_validator_test.go
  binding/form.go
  binding/form_mapping_test.go
  binding/header.go
  binding/validate_test.go
  binding/xml.go
  context_test.go
  errors_test.go
  fs.go
  gin.go
  ginS/gins.go
  gin_integration_test.go
  gin_test.go
  githubapi_test.go
  internal/bytesconv/bytesconv_test.go
  internal/fs/fs.go
  logger_test.go
  middleware_test.go
  mode.go
  render/html.go
  render/render_test.go
  routes_test.go
  tree_test.go
  utils_test.go
Labels: continuous-integration, github_actions

#4227 chore(bind): return 413 status code when error is `http.MaxBytesError`
  context.go
  context_test.go
  internal/json/go_json.go
  internal/json/json.go
  internal/json/jsoniter.go
  internal/json/sonic.go
Labels: enhancement

#4248 test(context): add cleanup for uploaded file in SaveUploadedFile test
  context_test.go
Labels: test

#3963 refactor(context): refactor `Keys` type to `map[any]any`
  context.go
  context_test.go
  logger.go
  logger_test.go
Labels: enhancement

#4252 perf(recover): replace bytes with strings in function for better performance
  recovery.go
  recovery_test.go
Labels: enhancement
