Repository gin-gonic/gin, pull requests merged in 2025-07, with the labels that each got.

#4290 feat: added `AbortWithStatusPureJSON()` in `Context`
  context.go
  context_test.go
Labels: feature

#4274 docs: added comment in doc.go
  doc.go
Labels: document

#4299 Fixed version number discrepancy
  debug.go
Labels: document

#4303 fix: remove impossible case
  mode.go
Labels: enhancement

#4291 test(route): add some test for routergroup
  routergroup_test.go
Labels: test

#4304 refactor(context): remove unused Context dependency in get method
  context.go
  context_test.go
Labels: refactor
