Repository gin-gonic/gin, pull requests merged in 2025-04, with the labels that each got.

#4205 docs: fix comment with AI
  binding/protobuf.go
  ginS/gins.go
Labels: document

#4175 perf: optimize AsciiJSON.Render method by using fmt.Appendf and reusing temp buffer
  render/json.go
Labels: performance

#4053 feat(fs): Implement loading HTML from http.FileSystem
  docs/doc.md
  gin.go
  ginS/gins.go
  gin_test.go
  internal/fs/fs.go
  internal/fs/fs_test.go
  render/html.go
  render/render_test.go
Labels: feature

#4224 refactor: replace magic number 128 with unicode.MaxASCII in AsciiJSON render
  render/json.go
Labels: refactor
