Repository gin-gonic/gin, pull requests merged in 2025-06, with the labels that each got.

#4143 refactor(recovery): extract Authorization header masking into maskAuthorization func
  recovery.go
  recovery_test.go
Labels: enhancement

#4261 docs: small changes
  gin.go
Labels: document

#4259 refactor(internal/bytesconv): replace rand usage with crypto/rand and rand.New
  internal/bytesconv/bytesconv_test.go
Labels: enhancement

#4266 fix(docs): missing go markdown codeblock
  docs/doc.md
Labels: document

#3391 feat: support custom json codec at runtime
  binding/form_mapping.go
  binding/json.go
  binding/json_test.go
  codec/json/api.go
  codec/json/go_json.go
  codec/json/json.go
  codec/json/jsoniter.go
  codec/json/sonic.go
  context_test.go
  docs/doc.md
  errors.go
  errors_test.go
  go.mod
  internal/json/go_json.go
  internal/json/json.go
  internal/json/jsoniter.go
  internal/json/sonic.go
  render/json.go
  render/render_test.go
Labels: feature

#4272 chroe: migrate yaml package to github.com/goccy/go-yaml
  binding/yaml.go
  go.mod
  go.sum
  render/render_test.go
  render/yaml.go
Labels: enhancement
